### ISSUE TITLE
Unlimited Time Mode

### ISSUE THREAD

**Issue by jaschdoc** [SSoelvsten/wordrow#28]

**Comment by SSoelvsten** [comment]
Maybe, what we can do is have difficulty levels? This can then be selected together with the language on the *Start Screen* planned for language selection?

- Easy : Unlimited Time
- Normal: As is
- Hard: Less time per word than you get now.

**Comment by SSoelvsten** [comment]
Alternatively, we could also consider

- **Unlimited Time:** ∞ minutes
- **Fixed time:** Full word time (quite similar to Text Twist)
- **Time Run:** Half word time + time per word (like the one right now)
