### ISSUE TITLE
Make text unselectable

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/wordrow#72]
As shown on [Stackoverflow](https://stackoverflow.com/a/6382492/13300643) one can make text unselectable in CSS. This would help us, especially when one plays with touch .

- [ ] Add this styling to the `CharBox` mixin.
- [ ] Add this styling to the scoreboard.

**Comment by tarunsamanta2k20** [comment]
I would like to work on this issue. Please assign it to me.
