### ISSUE TITLE
Alternative Name

### ISSUE THREAD

**Issue by SSoelvsten** [SSoelvsten/wordrow#8]
**Wordrow** is not bad, but maybe we will find a better idea later. Here is a list of interesting words to use for inspiration.

- **Text** : Word, Character, Letter, Alphabet, Type
- **Twist** : Shuffle, Mix, Blend, Mingle, Meld, Jumble, Permute, Transpose

From Wikipedia:

> An anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once. [...] Someone who creates anagrams may be called an "anagrammatist"

> The [Jumble](https://en.wikipedia.org/wiki/Jumble) is a puzzle found in many newspapers in the United States requiring the unscrambling of letters to find the solution. [...] Multiple anagramming is a technique used to solve some kinds of cryptograms, such as a [permutation cipher](https://en.wikipedia.org/wiki/Permutation_cipher), a [transposition cipher](https://en.wikipedia.org/wiki/Transposition_cipher), and the [Jefferson disk](https://en.wikipedia.org/wiki/Jefferson_disk).[[41]](https://en.wikipedia.org/wiki/Anagram#cite_note-41) Solutions may be computationally found using a [Jumble algorithm](https://en.wikipedia.org/wiki/Jumble_algorithm).

Furthermore, while in a different visual format this game is quite similar to a "Word Wheel' puzzle.

## Vote with emojis below

You may vote on multiple choices below

- :smile: : Anagrammer (A person who anagrams, I guess)
- :tada: : Anagame / Anagrame
- :heart: Wodler / Lowder / Rowled (anagrams of *wordle*)
- :rocket: : Word-Wheel (A different visual format for the same game)
- :eyes: Jumble / Wumble
- :+1: : Word-Row / Wordrow (as it is now)

**Comment by jaschdoc** [comment]
Settled on Wordrow?

**Comment by SSoelvsten** [comment]
Probably...
